let shopItemsData = [
  {
    id: "a",
    name: "Casual Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-1.jpg",
  },
  {
    id: "b",
    name: "Office Shirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-2.jpg",
  },
  {
    id: "c",
    name: "T Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-3.jpg",
  },
  {
    id: "d",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-4.jpg",
  },
  {
    id: "e",
    name: " Oates",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/s2.webp",
  },
  {
    id: "f",
    name: "Safoola Honey",
    price: 80,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/s1.webp",
  },
  {
    id: "g",
    name: "Fiction Books",
    price: 50,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/s3.webp",
  },
  {
    id: "h",
    name: "Microphone",
    price: 1000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/s4.webp",
  },
  {
    id: "i",
    name: "Nesecafe",
    price: 80,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/s5.jpeg",
  },
  {
    id: "j",
    name: "Acedmic Books",
    price: 40,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/s6.webp",
  },
  {
    id: "k",
    name: "Self Help Books",
    price: 50,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/s7.webp",
  },
  {
    id: "l",
    name: "Treadmill exercise",
    price: 1000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/s9.jpeg",
  },
  {
    id: "m",
    name: "Bicycle",
    price: 500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t2.jpeg",
  },
  {
    id: "n",
    name: "Pen",
    price: 50,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t6.jpeg",
  },
  {
    id: "o",
    name: "Smart Watch",
    price: 2000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/item3.jpg",
  },
  {
    id: "p",
    name: "Violin",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t7.jpeg",
  },
  {
    id: "q",
    name: "Teddy",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t8.jpeg",
  },
  {
    id: "r",
    name: "Sheet",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t9.jpeg",
  },
  {
    id: "s",
    name: "Violin (Toy)",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t10.jpeg",
  },
  {
    id: "t",
    name: "Car (Toy)",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t11.jpeg",
  },
  {
    id: "u",
    name: "Earth (Toy)",
    price: 50,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t12.jpeg",
  },
  {
    id: "v",
    name: "Bluetooth",
    price: 250,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/item1.jpeg",
  },
  {
    id: "w",
    name: "Keyboard",
    price: 250,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/item2.jpeg",
  },
  {
    id: "x",
    name: "Cemero",
    price: 50,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/s10.jpeg",
  },
  {
    id: "y",
    name: "Cartoon",
    price: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t3.jpeg",
  },
];


